import { dom, library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowUpRightFromSquare,
  faClipboardListCheck,
  faHandsHoldingDollar,
  faHouseBuilding,
  faPlusCircle,
  faPrint,
  faRightLeft,
  faScrewdriverWrench,
  faSpinner,
  faTrashCan,
  faWallet,
  faSearch,
  faPlus,
  faGripDotsVertical,
  faGlobe,
  faMoon,
  faBars,
  faHouse,
  faUserGroup,
} from "@fortawesome/pro-light-svg-icons";
import {
  faCalendarDays,
  faCircleExclamation,
  faCircleQuestion,
  faFileArrowUp,
  faFilePdf,
  faImage,
  faPenToSquare,
} from "@fortawesome/pro-regular-svg-icons";
import { faChevronLeft, faXmark } from "@fortawesome/pro-solid-svg-icons";

library.add(
  faPlusCircle,
  faPrint,
  faTrashCan,
  faCalendarDays,
  faCircleExclamation,
  faCircleQuestion,
  faPenToSquare,
  faChevronLeft,
  faXmark,
  faHouseBuilding,
  faRightLeft,
  faScrewdriverWrench,
  faClipboardListCheck,
  faWallet,
  faHandsHoldingDollar,
  faArrowUpRightFromSquare,
  faFileArrowUp,
  faImage,
  faFilePdf,
  faSpinner,
  faSearch,
  faPlus,
  faGripDotsVertical,
  faGlobe,
  faMoon,
  faBars,
  faHouse,
  faUserGroup
);

dom.watch();
